[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_coin_flip = "2NqZ9e5ubnuvNj5VeBya5wdEEwKZSEZJRnZamDsdZdVB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/friend/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 15000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

# Solana Randomness Service
[[test.validator.clone]]
address = "RANDMo5gFnqnXJW5Z52KNmd24sAo95KAd5VbiCtq5Rh"

# Sbv3 Program ID
[[test.validator.clone]]
address = "sbattyXrzedoNATfc4L31wC9Mhxsi1BmFhTiN8gDshx"

# Sbv3 ProgramStateAccount
[[test.validator.clone]]
address = "5MFs7RGTjLi1wtKNBFRtuLipCkkjs4YQwRRU9sjnbQbS"

# Sbv3 IDL
[[test.validator.clone]]
address = "5ExuoQR69trmKQfB95fDsUGsUrrChbGq9PFgt8qouncz"
